### ISSUE TITLE
Rename project

### ISSUE THREAD

**Issue by kaishin** [LlamaKit/LlamaKit#28]
This is not really an issue but more of a suggestion. I think the name and the README are not clear as to what this library currently does. `Result` has become a must-have for all my new projects, and it'd be nice if the library was called just that or something relatively close with an updated README and documentation.

Feel free to close at your own discretion.

**Comment by irace** [comment]
`Result` or `ResultKit`?

**Comment by lazerwalker** [comment]
I agree. I find the name particularly confusing since I tend to associate programming-related "llama" things so strongly with WinAmp.

I'd +1 `Result` or `ResultKit`. If you're worried about boxing (hah!) it it in to sounding like it's solely about Result and not Futures/function composition/etc, maybe something like `FunctionalKit`?

**Comment by swizzlr** [comment]
The recent trend of microframeworks makes LlamaKit the odd one out. ResultKit would be more descriptive, yet nod towards its roots as a "kit".

**Comment by felixjendrusch** [comment]
+1 `Result`, see also #6.

**Comment by robb** [comment]
:-1: for something as generic as `Result` or `ResultKit` for the module name. Swift is still pretty young and `Result.Result` may not end up being *the* Result everybody ends up using, just a waste of namespace imho and needlessly conflates the module name with the data type.
